#!/usr/bin/env python3
"""Deterministic, reviewable seed contracts. Never discover expectations from VeIR."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def module(body, result="i32", args="", name="main", prelude=""):
    types = ", ".join(part.split(": ", 1)[1] for part in args.split(", ")) if args else ""
    block = f"^entry({args}):\n" if args else ""
    return f'''"builtin.module"() ({{
{prelude}
  "llvm.func"() <{{sym_name = "{name}", function_type = !llvm.func<{result} ({types})>}}> ({{
{block}{body}
  }}) : () -> ()
}}) : () -> ()
'''


def constant(name, width, value):
    return f'    %{name} = "llvm.mlir.constant"() <{{value = {value} : i{width}}}> : () -> i{width}'


def returned(name, typ):
    return f'    "llvm.return"(%{name}) : ({typ}) -> ()'


def expected(width, value):
    return {"schema_version": 1, "outcome": "ok", "results": [{"kind": "int", "width": width, "value": str(value % (1 << width))}]}


def generate():
    tests, requirements = [], []
    def req(id, title, scope, stage, contract, operations=(), state="specified", source_groups=()):
        r = {"id": id, "title": title, "scope": scope, "stage": stage, "state": state,
             "contract": contract, "operations": list(operations), "source_groups": list(source_groups), "test_ids": []}
        requirements.append(r)
        return r

    def case(r, suffix, source, kind, **kwargs):
        id = r["id"] + "." + suffix
        relative = f"cases/generated/{id}.mlir"
        path = ROOT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        content = f"// Contract: {r['id']}\n// Generated by scripts/generate_cases.py; edit the generator, then regenerate.\n" + source
        path.write_text(content)
        tests.append({"id": id, "kind": kind, "input": relative,
                      "input_sha256": hashlib.sha256(content.encode()).hexdigest(), **kwargs})
        r["test_ids"].append(id)

    integer_ops = ["add", "sub", "mul", "and", "or", "xor", "shl", "lshr", "ashr", "udiv", "sdiv", "urem", "srem"]
    for op in integer_ops:
        op_name = "llvm." + op
        r = req(f"verify.{op}.scalar", f"{op}: scalar integer types", "llvm-compat", "verification",
                "Accept signless integer operands and a result of identical type at i1, i8, i32, i64 and i128.", [op_name])
        for width in [1, 8, 32, 64, 128]:
            typ = f"i{width}"
            body = f'    %r = "{op_name}"(%a, %b) : ({typ}, {typ}) -> {typ}\n' + returned("r", typ)
            case(r, typ, module(body, typ, f"%a: {typ}, %b: {typ}"), "verify", expect="accept")
        r = req(f"verify.{op}.vectors", f"{op}: fixed and scalable vectors", "llvm-compat", "verification",
                "Accept homogeneous fixed and scalable LLVM-compatible integer vectors; shape and element type must agree.", [op_name], source_groups=["MF-S02", "MF-S03"])
        for label, typ in [("fixed", "vector<4xi32>"), ("scalable", "vector<[4]xi32>")]:
            body = f'    %r = "{op_name}"(%a, %b) : ({typ}, {typ}) -> {typ}\n' + returned("r", typ)
            case(r, label, module(body, typ, f"%a: {typ}, %b: {typ}"), "verify", expect="accept")
        r = req(f"verify.{op}.mismatch", f"{op}: reject mismatched operand types", "llvm-compat", "verification",
                "Reject i32/i64 operand mismatch with a type diagnostic, not a parser crash or unrelated rejection.", [op_name])
        body = f'    %r = "{op_name}"(%a, %b) : (i32, i64) -> i32\n' + returned("r", "i32")
        case(r, "i32-i64", module(body, "i32", "%a: i32, %b: i64"), "verify", expect="reject",
             diagnostics={"reference": r"same type|type.*match", "veir": r"type|width"})
        r = req(f"roundtrip.{op}", f"{op}: preserve canonical IR", "llvm-compat", "roundtrip",
                "Strict registered parse/print is stable and preserves the reference's generic canonical IR.", [op_name])
        body = f'    %r = "{op_name}"(%a, %b) : (i32, i32) -> i32\n' + returned("r", "i32")
        case(r, "scalar", module(body, "i32", "%a: i32, %b: i32"), "roundtrip")

        r = req(f"execute.{op}", f"{op}: complete scalar results", "llvm-execution", "execution",
                "On explicitly defined inputs, match an independent Python integer expectation and LLVM execution for every bit at i8, i32, i64 and i128. These samples are not a proof for all inputs.", [op_name])
        for width in [8, 32, 64, 128]:
            mask = (1 << width) - 1
            pairs = [(0, 1), (mask, 1), (1 << (width - 1), 3), (mask - 4, 2)]
            for index, (a, b) in enumerate(pairs):
                signed = lambda n: n if n < 1 << (width - 1) else n - (1 << width)
                sa, sb = signed(a), signed(b)
                quotient = (abs(sa) // abs(sb)) * (-1 if (sa < 0) != (sb < 0) else 1)
                value = {"add": lambda: a+b, "sub": lambda: a-b, "mul": lambda: a*b,
                         "and": lambda: a&b, "or": lambda: a|b, "xor": lambda: a^b,
                         "shl": lambda: a<<b, "lshr": lambda: a>>b, "ashr": lambda: sa>>b,
                         "udiv": lambda: a//b, "sdiv": lambda: quotient,
                         "urem": lambda: a%b, "srem": lambda: sa-quotient*sb}[op]()
                typ = f"i{width}"
                body = "\n".join([constant("a", width, a), constant("b", width, b),
                                   f'    %r = "{op_name}"(%a, %b) : ({typ}, {typ}) -> {typ}', returned("r", typ)])
                case(r, f"i{width}-{index}", module(body, typ), "differential", result_width=width,
                     defined_behavior=True, expected_result=expected(width, value))

    for op in ["add", "sub", "mul", "shl", "udiv", "sdiv", "lshr", "ashr", "or"]:
        if op in {"add", "sub", "mul", "shl"}:
            flags = [("nsw", "overflowFlags = #llvm.overflow<nsw>"), ("nuw", "overflowFlags = #llvm.overflow<nuw>"), ("both", "overflowFlags = #llvm.overflow<nsw, nuw>")]
        else:
            flags = [("disjoint", "isDisjoint")] if op == "or" else [("exact", "isExact")]
        r = req(f"roundtrip.{op}.flags", f"{op}: preserve semantic flags", "llvm-compat", "roundtrip",
                "Preserve the standard LLVM dialect property encoding and its meaning through both parsers; dropping a flag is failure.", ["llvm."+op], source_groups=["MF-S09"])
        for label, flag in flags:
            body = f'    %r = "llvm.{op}"(%a, %b) <{{{flag}}}> : (i32, i32) -> i32\n' + returned("r", "i32")
            case(r, label, module(body, "i32", "%a: i32, %b: i32"), "roundtrip")

    for op in ["fadd", "fsub", "fmul", "fdiv", "frem"]:
        r = req(f"verify.{op}.types", f"{op}: floating-point types", "llvm-compat", "verification",
                "Accept homogeneous f16, bf16, f32, f64 and f128 operands; acceptance is distinct from execution support.", ["llvm."+op], source_groups=["MF-S04"])
        for typ in ["f16", "bf16", "f32", "f64", "f128"]:
            body = f'    %r = "llvm.{op}"(%a, %b) : ({typ}, {typ}) -> {typ}\n' + returned("r", typ)
            case(r, typ, module(body, typ, f"%a: {typ}, %b: {typ}"), "verify", expect="accept")
        r = req(f"roundtrip.{op}.fastmath", f"{op}: fast-math flags", "llvm-compat", "roundtrip",
                "Preserve none, nnan, ninf, nsz and fast flag sets in canonical MLIR, without inferring semantic correctness.", ["llvm."+op], source_groups=["MF-S10"])
        for flag in ["none", "nnan", "ninf", "nsz", "fast"]:
            body = f'    %r = "llvm.{op}"(%a, %b) <{{fastmathFlags = #llvm.fastmath<{flag}>}}> : (f64, f64) -> f64\n' + returned("r", "f64")
            case(r, flag, module(body, "f64", "%a: f64, %b: f64"), "roundtrip")

    flag_sets = [
        ("nsw", "overflowFlags = #llvm.overflow<nsw>", ["add", "sub", "mul", "shl"]),
        ("nuw", "overflowFlags = #llvm.overflow<nuw>", ["add", "sub", "mul", "shl"]),
        ("nsw-nuw", "overflowFlags = #llvm.overflow<nsw, nuw>", ["add", "sub", "mul", "shl"]),
        ("exact", "isExact", ["udiv", "sdiv", "lshr", "ashr"]),
        ("disjoint", "isDisjoint", ["or"]),
    ]
    for label, flag, ops in flag_sets:
        r = req(f"execute.flags.{label}", f"{label}: defined flagged execution", "llvm-execution", "execution",
                "Use the standard property spelling on non-violating inputs and compare the entire result with LLVM and a mathematical expectation. Poison-producing inputs have separate model contracts.", ["llvm."+op for op in ops])
        for op in ops:
            a, b = (8, 2) if label == "exact" else (4, 2)
            value = {"add": a+b, "sub": a-b, "mul": a*b, "shl": a<<b, "udiv": a//b, "sdiv": a//b, "lshr": a>>b, "ashr": a>>b, "or": a|b}[op]
            body = "\n".join([constant("a", 64, a), constant("b", 64, b), f'    %r = "llvm.{op}"(%a, %b) <{{{flag}}}> : (i64, i64) -> i64', returned("r", "i64")])
            case(r, op, module(body, "i64"), "differential", result_width=64, defined_behavior=True, expected_result=expected(64, value))

    for op, source_width, target_width in [("trunc", 128, 32), ("zext", 8, 128), ("sext", 8, 128)]:
        r = req(f"execute.{op}", f"{op}: bit-accurate conversion", "llvm-execution", "execution",
                "Match LLVM and mathematical truncation/extension at zero, positive maximum, sign bit and all ones.", ["llvm."+op])
        for index, a in enumerate([0, (1 << (source_width-1))-1, 1 << (source_width-1), (1 << source_width)-1]):
            value = a - (1 << source_width) if op == "sext" and a >= 1 << (source_width-1) else a
            body = "\n".join([constant("a", source_width, a), f'    %r = "llvm.{op}"(%a) : (i{source_width}) -> i{target_width}', returned("r", f"i{target_width}")])
            case(r, str(index), module(body, f"i{target_width}"), "differential", result_width=target_width, defined_behavior=True, expected_result=expected(target_width, value))

    predicates = ["eq", "ne", "slt", "sle", "sgt", "sge", "ult", "ule", "ugt", "uge"]
    for pred, name in enumerate(predicates):
        r = req(f"execute.icmp.{name}", f"icmp {name}: signedness and equality", "llvm-execution", "execution",
                "Compare signed and unsigned interpretations, returning the full i1 result; no exit-code approximation.", ["llvm.icmp"])
        for index, (a, b) in enumerate([(255, 1), (1, 255), (128, 128), (0, 0)]):
            x, y = ((a if a < 128 else a-256), (b if b < 128 else b-256)) if name.startswith("s") else (a, b)
            value = {"eq": x == y, "ne": x != y, "lt": x < y, "le": x <= y, "gt": x > y, "ge": x >= y}[name.lstrip("su")]
            body = "\n".join([constant("a", 8, a), constant("b", 8, b), f'    %r = "llvm.icmp"(%a, %b) <{{predicate = {pred} : i64}}> : (i8, i8) -> i1', returned("r", "i1")])
            case(r, str(index), module(body, "i1"), "differential", result_width=1, defined_behavior=True, expected_result=expected(1, int(value)))

    for op in ["intr.ctpop", "intr.bswap", "intr.bitreverse"]:
        r = req(f"execute.{op}", f"{op}: integer intrinsics", "llvm-execution", "execution",
                "Match independently calculated popcount, byte swap or bit reversal on defined i64 inputs.", ["llvm."+op])
        for index, a in enumerate([0, 0x0123456789ABCDEF, (1 << 64)-1, 1 << 63]):
            value = a.bit_count() if op == "intr.ctpop" else int.from_bytes(a.to_bytes(8, "little"), "big") if op == "intr.bswap" else int(f"{a:064b}"[::-1], 2)
            body = "\n".join([constant("a", 64, a), f'    %r = "llvm.{op}"(%a) : (i64) -> i64', returned("r", "i64")])
            case(r, str(index), module(body, "i64"), "differential", result_width=64, defined_behavior=True, expected_result=expected(64, value))

    # Small programs exercise interactions that operation-by-operation tests miss.
    programs = {}
    programs["select"] = ("\n".join([constant("c", 1, 1), constant("a", 64, 1099511628031), constant("b", 64, 17), '    %r = "llvm.select"(%c, %a, %b) : (i1, i64, i64) -> i64', returned("r", "i64")]), 64, 1099511628031, ["llvm.select"])
    programs["memory"] = ("\n".join([constant("one", 32, 1), constant("a", 64, 1099511628031), '    %p = "llvm.alloca"(%one) <{elem_type = i64, alignment = 8 : i64}> : (i32) -> !llvm.ptr', '    "llvm.store"(%a, %p) <{alignment = 8 : i64}> : (i64, !llvm.ptr) -> ()', '    %r = "llvm.load"(%p) <{alignment = 8 : i64}> : (!llvm.ptr) -> i64', returned("r", "i64")]), 64, 1099511628031, ["llvm.alloca", "llvm.store", "llvm.load"])
    programs["branch"] = ("\n".join([constant("c", 1, 1), constant("a", 32, 1025), constant("b", 32, 1026), '    "llvm.cond_br"(%c, %a, %b) [^yes, ^no] <{operandSegmentSizes = array<i32: 1, 1, 1>}> : (i1, i32, i32) -> ()', '  ^yes(%v: i32):', '    "llvm.br"(%v) [^exit] : (i32) -> ()', '  ^no(%w: i32):', '    "llvm.br"(%w) [^exit] : (i32) -> ()', '  ^exit(%r: i32):', returned("r", "i32")]), 32, 1025, ["llvm.br", "llvm.cond_br"])
    programs["fold-and-cse"] = ("\n".join([constant("a", 64, 1099511628031), constant("zero", 64, 0), '    %x = "llvm.add"(%a, %zero) : (i64, i64) -> i64', '    %y = "llvm.add"(%a, %zero) : (i64, i64) -> i64', '    %r = "llvm.or"(%x, %y) : (i64, i64) -> i64', returned("r", "i64")]), 64, 1099511628031, ["llvm.add", "llvm.or"])
    for name, (body, width, value, ops) in programs.items():
        r = req(f"program.{name}", f"Program: {name}", "llvm-execution", "execution",
                "Execute this defined program against LLVM, including every returned bit and its control/data dependencies. Observations currently exclude external I/O and final memory.", ops)
        case(r, "original", module(body, f"i{width}"), "differential", result_width=width, defined_behavior=True, expected_result=expected(width, value))
        r = req(f"transform.{name}", f"Optimization preserves {name}", "transformations", "transformation",
                "canonicalize,cse,dce produces verified IR and preserves the original program's independently measured return value. This is bounded execution evidence, not a pass proof.", ops)
        case(r, "optimized", module(body, f"i{width}"), "pipeline", pipeline="canonicalize,cse,dce", result_width=width, defined_behavior=True, expected_result=expected(width, value))

    # UB/poison are specified by VeIR's model; never run LLVM on these as an oracle.
    for op, flag, a, b in [("add", "overflowFlags = 1 : i32", 127, 1), ("add", "overflowFlags = 2 : i32", 255, 1), ("udiv", "isExact", 7, 2), ("or", "isDisjoint", 3, 1)]:
        suffix = "nsw" if "= 1" in flag else "nuw" if "= 2" in flag else "exact" if op == "udiv" else "disjoint"
        r = req(f"model.poison.{suffix}", f"Model: {suffix} violation produces poison", "veir-model", "execution",
                "VeIR's documented flag encoding produces a typed poison result for this violating input; agreement with all LLVM poison contexts remains a separate obligation.", ["llvm."+op])
        body = "\n".join([constant("a", 8, a), constant("b", 8, b), f'    %r = "llvm.{op}"(%a, %b) <{{{flag}}}> : (i8, i8) -> i8', returned("r", "i8")])
        case(r, "violation", module(body, "i8"), "interpret", expected_result={"schema_version": 1, "outcome": "ok", "results": [{"kind": "int", "width": 8, "poison": True}]})
    r = req("model.ub.divide-zero", "Model: division by zero is UB", "veir-model", "execution",
            "Report undefined_behavior explicitly, without conflating it with success, unsupported interpretation or a crash.", ["llvm.udiv"])
    body = "\n".join([constant("a", 32, 1), constant("b", 32, 0), '    %r = "llvm.udiv"(%a, %b) : (i32, i32) -> i32', returned("r", "i32")])
    case(r, "zero", module(body), "interpret", expected_result={"schema_version": 1, "outcome": "undefined_behavior", "results": []})

    r = req("model.byte-poison", "Model: direct byte poison construction", "veir-model", "execution",
            "The accepted byte type must produce a value with every bit marked poison when constructed by llvm.mlir.poison; unsupported interpretation remains open.", ["llvm.mlir.poison"])
    body = '    %r = "llvm.mlir.poison"() : () -> !llvm.byte<16>\n' + returned("r", "!llvm.byte<16>")
    case(r, "i16", module(body, "!llvm.byte<16>"), "interpret", expected_result={"schema_version": 1, "outcome": "ok", "results": [{"kind": "byte", "width": 16, "value": "0", "poison_mask": "65535"}]})
    r = req("execute.pointer-casts", "Null pointer integer round-trip", "llvm-execution", "execution",
            "On the explicitly selected 64-bit reference profile, converting integer zero to a pointer and back returns zero. This does not specify non-null pointer provenance.", ["llvm.inttoptr", "llvm.ptrtoint"])
    body = "\n".join([constant("zero", 64, 0), '    %ptr = "llvm.inttoptr"(%zero) : (i64) -> !llvm.ptr', '    %r = "llvm.ptrtoint"(%ptr) : (!llvm.ptr) -> i64', returned("r", "i64")])
    case(r, "null", module(body, "i64"), "differential", result_width=64, defined_behavior=True, expected_result=expected(64, 0))

    # Deliberately visible contracts without evidence; no guessed green checkmarks.
    backlog = [
        ("contract.supported-programs", "Choose required programs and dialects", "project", "verification", "needs_decision", "Approve concrete end-to-end programs, input languages and excluded dialects. MLIR-wide parity is not an assumed requirement."),
        ("contract.observations", "Approve observable behavior", "project", "execution", "needs_decision", "Choose returned values, final memory, external calls, I/O, termination and divergence; define the supported ABI and data layout."),
        ("contract.refinement", "Approve equality/refinement and failure semantics", "project", "proof", "needs_decision", "Specify the correctness relation and review the .fail branch of Interp.isRefinedBy, which currently allows any target result. Missing interpretation cannot count as completion."),
        ("contract.trusted-boundary", "Approve the trusted boundary", "project", "proof", "needs_decision", "Name the parser, interpreter semantics, solver assumptions, axioms, external compiler and hardware trusted by each guarantee."),
        ("contract.compatibility-version", "Choose the compatibility version policy", "project", "verification", "needs_decision", "Decide whether MLIR compatibility targets a release, pinned commit or a moving range. Current measurements name one exact reference build."),
        ("proof.pass-correctness", "Pass correctness with an axiom audit", "transformations", "proof", "needs_tests", "Connect required pass theorems to the approved relation, compile them and audit transitive axioms. A successful ordinary Lean build does not establish an axiom-free theorem."),
        ("proof.model-fidelity", "Validate the semantic model boundary", "veir-model", "proof", "needs_decision", "Review integer, floating-point, memory, poison, undef, UB and unsupported behavior against the chosen external semantics, then name the fidelity claim."),
        ("execution.floating-point", "Floating-point semantic coverage", "llvm-execution", "execution", "needs_tests", "Cover signed zeros, infinities, NaNs, rounding and fast-math assumptions with an independent suitable oracle; current type tests are insufficient."),
        ("execution.vector-aggregate", "Vector and aggregate execution", "llvm-execution", "execution", "needs_tests", "Observe vector lanes and aggregate components, including poison; parser registration alone is insufficient."),
        ("execution.memory-model", "Memory, pointers and aliasing", "llvm-execution", "execution", "needs_decision", "Approve allocation lifetime, provenance, alignment, aliasing, atomics and observable final memory before declaring memory conformance."),
        ("program.sqlite", "SQLite end-to-end milestone", "programs", "regression", "needs_decision", "Select a pinned SQLite program, compilation pipeline, workloads, expected observations and success criteria. Structural parse counts are not this milestone."),
        ("program.llvm-corpus", "Pinned LLVM corpus regression", "programs", "regression", "needs_tests", "Import strict registered round-trip results with complete manifests, exact revisions and explicit failures; exclude permissive parses from strict coverage."),
        ("core.ir-invariants", "Core IR and rewrite invariants", "core", "verification", "needs_tests", "Map existing unit tests to SSA, dominance, use lists, region ownership, cloning and mutation obligations; file counts alone do not close these obligations."),
        ("core.other-dialects", "Scope the other VeIR dialects", "core", "verification", "needs_decision", "Choose compatibility and correctness goals for arith, func, cf, machine dialects and VeIR-specific dialects separately."),
    ]
    for id, title, scope, stage, state, contract in backlog:
        req(id, title, scope, stage, contract, state=state)

    # All supplied observations remain traceable, with no assumption that a generic
    # smoke test closes every property or every operation in a source group.
    source = ROOT / "requirements/sources/mathieu.json"
    if source.exists():
        for group in json.loads(source.read_text())["groups"]:
            req("mathieu." + group["id"], group["title"], "mathieu-audit", "verification",
                "Audit this source observation against the pinned reference; select explicit positive controls, invalid cases and affected operations before closing it. " + group.get("description", ""),
                operations=[op["name"] if isinstance(op, dict) else op for op in group.get("operations", [])], state="needs_tests", source_groups=[group["id"]])

    for path in sorted((ROOT / "requirements/imports").glob("*.json")):
        imported = json.loads(path.read_text())
        requirements.extend(imported["requirements"])
        tests.extend(imported["tests"])
    # Hand-authored project contracts live separately from generated fixtures.
    # Overrides are deliberate source changes and therefore start a new cohort.
    overrides = ROOT / "requirements/overrides.json"
    if overrides.exists():
        changes = json.loads(overrides.read_text())
        indexed = {r["id"]: r for r in requirements}
        for id, updates in changes.get("requirements", {}).items():
            if id not in indexed or "id" in updates or "test_ids" in updates:
                raise ValueError(f"Invalid contract override: {id}")
            indexed[id].update(updates)

    project = json.loads((ROOT / "requirements/project.json").read_text())
    registry = {"schema_version": 1, **project, "requirements": requirements, "tests": tests}
    (ROOT / "requirements").mkdir(exist_ok=True)
    (ROOT / "requirements/registry.json").write_text(json.dumps(registry, indent=2) + "\n")
    expected_paths = {ROOT / t["input"] for t in tests}
    for path in (ROOT / "cases/generated").glob("*.mlir"):
        if path not in expected_paths:
            path.unlink()
    print(f"Generated {len(tests)} checks for {len(requirements)} requirements")


if __name__ == "__main__":
    generate()
